export enum ApiProxyEndpoint {
  Cluster = '/api/cluster',
  Facility = '/api/facility',
  FacilityAssistant = '/api/facility-assistant',
  FacilityAssistantSchedule = '/api/facility-assistant-schedule',
  Booking = '/api/booking',
  Property = '/api/property',
  Unit = '/api/unit',
  UnitType = 'api/unit-type',
  Contact = '/api/contact',
  Tenant = '/api/tenant',
  ContactPhone = '/api/contact-phone',
  ContactEmail = '/api/contact-email',
  Role = '/api/role',
  RoleGroup = '/api/role-group',
  Template = '/api/template',
}
